"""
Database models for stock signal app.
"""

from datetime import datetime
from decimal import Decimal

from sqlalchemy import (
    Column,
    DateTime,
    Enum,
    ForeignKey,
    Integer,
    Numeric,
    String,
    Text,
)
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()


class Signal(Base):
    """
    Trading signal record.
    
    Stores technical signals generated by the indicator engine.
    """
    __tablename__ = "signals"
    
    id = Column(Integer, primary_key=True)
    ticker = Column(String(10), nullable=False, index=True)
    timestamp = Column(DateTime, default=datetime.utcnow, nullable=False)
    signal_type = Column(String(20), nullable=False)  # bullish/bearish/neutral
    confidence = Column(Numeric(5, 2), nullable=False)
    technical_score = Column(Numeric(5, 2), nullable=False)
    
    # AI-generated reasoning
    ai_reasoning = Column(Text, nullable=True)
    reasons = Column(Text, nullable=True)  # Technical reasons for signal
    
    # Status
    status = Column(String(20), default="pending")  # pending/approved/executed
    trade_id = Column(Integer, nullable=True)  # Link to executed trade
    
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(
        DateTime,
        default=datetime.utcnow,
        onupdate=datetime.utcnow,
    )
    
    def __repr__(self):
        return f"<Signal(ticker={self.ticker}, type={self.signal_type})>"


class OptionChain(Base):
    """
    Option chain data for a ticker.
    
    Stores option contracts with their Greeks and pricing.
    """
    __tablename__ = "option_chains"
    
    id = Column(Integer, primary_key=True)
    ticker = Column(String(10), nullable=False, index=True)
    expiry_date = Column(DateTime, nullable=False, index=True)
    strike_price = Column(Numeric(10, 2), nullable=False)
    right = Column(String(1), nullable=False)  # C/P
    conid = Column(Integer, nullable=False)  # IBKR contract ID
    
    # Market data
    bid = Column(Numeric(10, 2), default=Decimal("0.00"))
    ask = Column(Numeric(10, 2), default=Decimal("0.00"))
    volume = Column(Integer, default=0)
    open_interest = Column(Integer, default=0)
    
    # Greeks
    iv = Column(Numeric(10, 4), default=Decimal("0.0000"))  # Implied Volatility
    delta = Column(Numeric(10, 4), default=Decimal("0.0000"))
    gamma = Column(Numeric(10, 4), default=Decimal("0.0000"))
    theta = Column(Numeric(10, 4), default=Decimal("0.0000"))
    vega = Column(Numeric(10, 4), default=Decimal("0.0000"))
    
    # Metadata
    underlying_price = Column(Numeric(10, 2), nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow)
    
    def __repr__(self):
        return f"<OptionChain(ticker={self.ticker}, expiry={self.expiry_date})>"


class Trade(Base):
    """
    Trade execution record.
    
    Stores trade orders and their execution status.
    """
    __tablename__ = "trades"
    
    id = Column(Integer, primary_key=True)
    signal_id = Column(Integer, ForeignKey("signals.id"), nullable=False)
    
    # Trade details
    ticker = Column(String(10), nullable=False, index=True)
    quantity = Column(Integer, nullable=False)
    side = Column(String(4), nullable=False)  # buy/sell
    order_type = Column(String(10), default="market")  # market/limit
    
    # Execution details
    status = Column(String(20), default="pending")
    ib_order_id = Column(String(50), nullable=True)
    filled_qty = Column(Integer, default=0)
    avg_fill_price = Column(Numeric(10, 2), nullable=True)
    
    # Order details
    order_intent = Column(Text, nullable=False)  # JSON string
    
    created_at = Column(DateTime, default=datetime.utcnow)
    filled_at = Column(DateTime, nullable=True)
    
    def __repr__(self):
        return f"<Trade(ticker={self.ticker}, status={self.status})>"


class Position(Base):
    """
    Current position record.
    
    Tracks open positions and their performance.
    """
    __tablename__ = "positions"
    
    id = Column(Integer, primary_key=True)
    ticker = Column(String(10), nullable=False, index=True)
    position_qty = Column(Integer, nullable=False)
    avg_cost = Column(Numeric(10, 2), nullable=False)
    
    # Current values
    current_price = Column(Numeric(10, 2), nullable=True)
    unrealized_pnl = Column(Numeric(10, 2), nullable=True)
    
    # Position metadata
    direction = Column(String(10), default="long")  # long/short
    trade_id = Column(Integer, ForeignKey("trades.id"), nullable=True)
    
    last_updated = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    
    def __repr__(self):
        return f"<Position(ticker={self.ticker}, qty={self.position_qty})>"


class MarketDataCandle(Base):
    """
    OHLCV candle data for technical analysis.
    
    Stores historical market data for backtesting and analysis.
    """
    __tablename__ = "market_data_candles"
    
    id = Column(Integer, primary_key=True)
    ticker = Column(String(10), nullable=False, index=True)
    timestamp = Column(DateTime, nullable=False, index=True)
    
    # OHLCV data
    open = Column(Numeric(10, 2), nullable=False)
    high = Column(Numeric(10, 2), nullable=False)
    low = Column(Numeric(10, 2), nullable=False)
    close = Column(Numeric(10, 2), nullable=False)
    volume = Column(Integer, nullable=True)
    
    # Timeframe identifier
    timeframe = Column(String(10), default="1d")
    
    created_at = Column(DateTime, default=datetime.utcnow)
    
    def __repr__(self):
        return f"<Candle(ticker={self.ticker}, date={self.timestamp})>"


class TradeSignal(Base):
    """
    Trade signal generated after analysis.
    
    Links signals to trade execution workflow.
    """
    __tablename__ = "trade_signals"
    
    id = Column(Integer, primary_key=True)
    signal_id = Column(Integer, ForeignKey("signals.id"), nullable=False)
    trade_plan = Column(Text, nullable=True)  # JSON string
    ai_recommendation = Column(Text, nullable=True)
    
    status = Column(String(20), default="pending")  # pending/approved/rejected
    approved_at = Column(DateTime, nullable=True)
    
    created_at = Column(DateTime, default=datetime.utcnow)
    
    def __repr__(self):
        return f"<TradeSignal(id={self.id}, status={self.status})>"


class WebhookLog(Base):
    """
    Log for TradingView webhooks.
    
    Tracks incoming webhook events for debugging.
    """
    __tablename__ = "webhook_logs"
    
    id = Column(Integer, primary_key=True)
    event_type = Column(String(50), nullable=False)  # alert/quote/etc
    payload = Column(Text, nullable=True)
    processed = Column(Integer, default=0)  # 0: not processed, 1: processed
    error = Column(Text, nullable=True)
    
    created_at = Column(DateTime, default=datetime.utcnow)
    
    def __repr__(self):
        return f"<WebhookLog(event_type={self.event_type})>"
