from datetime import datetime
from typing import Protocol

from app.services.background_jobs import SweepCandidate


class WorkflowSweepAdapter(Protocol):
    async def list_reconciliation_candidates(self) -> list[SweepCandidate]: ...
    async def reconcile(self, workflow_id: str) -> str | None: ...
    async def list_stale_candidates(self, stale_before: datetime) -> list[SweepCandidate]: ...
    async def handle_stale(self, workflow_id: str) -> str | None: ...


class ExecutionSweepAdapter(Protocol):
    async def list_reconciliation_candidates(self) -> list[SweepCandidate]: ...
    async def reconcile(self, execution_id: str) -> str | None: ...


class PositionSweepAdapter(Protocol):
    async def list_reconciliation_candidates(self) -> list[SweepCandidate]: ...
    async def reconcile(self, execution_id: str) -> str | None: ...
    async def list_exit_candidates(self) -> list[SweepCandidate]: ...
    async def monitor_exit(self, position_id: str) -> str | None: ...
