from dataclasses import dataclass
from datetime import datetime
from typing import Literal

SweepCandidateType = Literal["WORKFLOW", "EXECUTION", "POSITION"]

WORKFLOW_RECONCILIATION_STATUSES = (
    "APPROVED", "INTENT_CREATED", "EXECUTION_CREATED", "SUBMISSION_PENDING",
    "SUBMITTED", "PARTIALLY_FILLED", "FILLED", "POSITION_RECONCILED", "EXIT_MONITORING",
)
EXECUTION_RECONCILIATION_STATUSES = (
    "SUBMISSION_PENDING", "SUBMITTED", "ACKNOWLEDGED", "PARTIALLY_FILLED", "CANCEL_PENDING",
)
POSITION_RECONCILIATION_STATUSES = ("PARTIALLY_FILLED", "FILLED")
NON_TERMINAL_WORKFLOW_STATUSES = (
    "CREATED", "RECOMMENDATION_READY", "RISK_APPROVED", "AWAITING_APPROVAL", "APPROVED",
    "INTENT_CREATED", "EXECUTION_CREATED", "SUBMISSION_PENDING", "SUBMITTED",
    "PARTIALLY_FILLED", "FILLED", "POSITION_RECONCILED", "EXIT_MONITORING",
    "EXIT_SIGNAL_CREATED", "EXIT_INTENT_CREATED", "EXIT_EXECUTION_CREATED",
)


@dataclass(frozen=True)
class SweepCandidate:
    candidate_id: str
    candidate_type: SweepCandidateType
    status: str
    account_id: str | None
    updated_at: datetime | None
