from typing import Protocol

from app.services.broker_events.models import BrokerEvent


class BrokerEventStore(Protocol):
    async def reserve(self, idempotency_key: str, event_id: str) -> None: ...
    async def save(self, event: BrokerEvent) -> None: ...
    async def get(self, event_id: str) -> BrokerEvent | None: ...
    async def get_by_idempotency_key(self, idempotency_key: str) -> BrokerEvent | None: ...
    async def list_ids_by_statuses(self, statuses: tuple[str, ...], *, limit: int) -> list[str]: ...
    async def list_ids_for_broker_order(self, broker_order_id: str, *, limit: int) -> list[str]: ...
    async def list_ids_for_execution(self, execution_id: str, *, limit: int) -> list[str]: ...
    async def release(self, idempotency_key: str) -> None: ...
